### ISSUE TITLE
Layout for Home Page and Navbar

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#1]
### Value Proposition

As a User, I need to land on the home page including a welcome message and see a navigation bar which I use to gather an overview of the different pages of the app.

### Description

![Bildschirmfoto 2022-11-28 um 11 17 26](https://user-images.githubusercontent.com/115008408/204253013-feff408d-58c1-4a6f-a8d9-03b85200d685.png)

### Acceptance Criteria

- [ ] The navbar is visible with 4 items: 
   - [ ] Home
   - [ ] Add spendings
   - [ ] Tips & Tricks
   - [ ] Rewards
 - [ ] The logo and a welcome are visible on the home page
 - [ ] The nav items are linked to own pages
 - [ ] When I am on a certain page, the corresponding nav item should be highlighted
 - [ ] The "Add spendings", "Tips & Tricks" and "Rewards" pages contain "Under construction" messages

### Tasks

(for developers team)

- [ ] Create a new branch
- [ ] Create the navbar component
- [ ] Add logo and welcome message to the home page
- [ ] Create routes for "Add spendings", "Tips & Tricks" and "Rewards" pages
- [ ] Add "Under construction" messages to the pages
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**S**
