### ISSUE TITLE
US3: Header incl. linked logo

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#10]
### Value Proposition

As a User, I want to see a header with the app logo through which I can return to the home page from any page.

### Description

![Bildschirmfoto 2022-12-01 um 10 08 06](https://user-images.githubusercontent.com/115008408/205011999-d82d6366-4fef-4dd5-97ab-ec5cef7de822.png)

### Acceptance Criteria

- [ ] Create a header component
- [ ] Add the app logo to the header component
- [ ] Link the home page in the app logo

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Create header component
- [ ] Add logo to the header and link the home page in there
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**S**
