### ISSUE TITLE
US5: Submit Form with Routing

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#13]
### Value Proposition

**As a** visitor
**I need** the possibility to submit the form
**to be able to** add new spendings

### Description

![Bildschirmfoto 2022-12-02 um 10 03 31](https://user-images.githubusercontent.com/115008408/205256064-0f8775c1-df77-46f3-b766-20d7adb24b3f.png)

![Bildschirmfoto 2022-12-02 um 09 59 37](https://user-images.githubusercontent.com/115008408/205255413-ccaf3d36-78c2-4ea5-92ef-67a8757c7850.png)

### Acceptance Criteria

- [ ] After having filled the form, the user is able to click on the submit button
- [ ] The user is redirected to the corresponding category page
- [ ] The spendings history for the category is displayed on the category page

### Tasks

- [ ] Add on submit handler to form
- [ ] Add logic to create category page
- [ ] Create routing from submit button to category page

### Sizing/Complexity

**M**
