### ISSUE TITLE
US6: Pass Form Data to Category Pages

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#15]
### Value Proposition

**As a** User, 
**I need** to see the spendings overview for a certain category (i.e. "Clothes") on the corresponding category page. Directly from each category page I should be able to go back to the "Add Spendings" page.

### Description

![Bildschirmfoto 2022-12-04 um 13 42 44](https://user-images.githubusercontent.com/115008408/205491063-3cc09762-43bf-471b-91d5-3ffe18384735.png)

### Acceptance Criteria

- [ ] After having filled ALL four form fields, the user is redirected to the overview page matching the selected category
- [ ] The user sees on each category page the form data for the corresponding category (i.e. "Clothes")
- [ ] At the bottom of all category pages, the user sees a button to go back to the "Add Spendings" page

### Tasks

- [ ] Create category pages
- [ ] Create routing from submit button to the corresponding category page
- [ ] Add logic that passes form data to the selected category page
- [ ] On the category pages, add buttons to create routing back to "Add Spendings" page

### Sizing/Complexity

**M**
