### ISSUE TITLE
Form to add Spendings

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#2]
### Value Proposition

As a user, I need a form to be able to start adding my first spendings. 

### Description

![Bildschirmfoto 2022-11-28 um 12 48 30](https://user-images.githubusercontent.com/115008408/204270546-bea4fbb5-e656-4ec9-bf88-3ba93f4894bd.png)

### Acceptance Criteria

- [ ] In the "Add Spendings" page ("+" navbar icon), a form replaces the initial "Under construction" message:
- [ ] The form contains for input fields and the corresponding labels: 
  - [ ] Title (input type field)
  - [ ] Amount (input type field that only accepts numerical values, show warning if this is not the case)
  - [ ] Date (calendar type field)
  - [ ] Category (select type field with a drop-down list including the predefined categories)
- [ ] All form Inputs are required, show warning if empty.
- [ ] The form contains a "Submit" button
- [ ] The content from the form is saved in local storage

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Create a form with the required fields and submit button
- [ ] Save user input in local storage
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**M**

**Comment by MaxMer25** [comment]
looks good to me, little typo in second acceptance criteria (four instead of for) :)
