### ISSUE TITLE
US11: Highlight Active Page

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#28]
### Value Proposition

**As a** visitor 
**I need** to see in the navbar on which page I am currently

### Description

<img width="186" alt="Bildschirmfoto 2022-12-19 um 11 13 14" src="https://user-images.githubusercontent.com/115008408/208402006-f539e39d-b000-4c0b-97fb-48ff4563e5f7.png">

### Acceptance Criteria

- [ ] Highlight navbar item for a page, when this is active
- [ ] When the active page changes, the highlighted navbar item changes accordingly

### Tasks

- [ ] Add highlighting property to the navbar component
- [ ] Create logic to apply highlighting property when the page is active

### Sizing/Complexity

**S**
