### ISSUE TITLE
Create Log Entries for Spendings

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#3]
### Value Proposition

As a user, I need to see an overview of my spendings in the corresponding category page (food, clothes, gasoline, etc.).

### Description

![Bildschirmfoto 2022-11-28 um 14 46 05](https://user-images.githubusercontent.com/115008408/204293075-9c002021-4608-4c5e-aa3b-b82ffc034065.png)

### Acceptance Criteria

- [ ] Each spendings category (food, clothes, gasoline, etc.) has a dedicated page
- [ ] The data entered into the [spendings form](https://github.com/marcos-de-barros-vioque/capstone/issues/2) by the visitor is used to create a new log entry in the corresponding category page

### Tasks

- [ ] Pull the remote repository
- [ ] Create cards with the form's data (createElement)
- [ ] Create category pages
- [ ] Append the cards to the corresponding category pages
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**M**
