### ISSUE TITLE
Spendings Overview on Home Page

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#4]
### Value Proposition

As a user, I want to see an overview of my spendings in the current month at a first glance on the home page.

### Description

![Bildschirmfoto 2022-11-28 um 15 37 16](https://user-images.githubusercontent.com/115008408/204304685-a98838ff-f1c4-43c7-b82e-a000b7005232.png)

### Acceptance Criteria

- [ ] After having submitted the first spending, the initial content of the home page incl. welcome message is replaced by the category card displaying the spendings for the selected category.
- [ ] A counter in the card displays the total amount of spendings for the corresponding category 

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Create card with the following data: 
  - [ ] Category name
  - [ ] Current month
  - [ ] Spendings counter 
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**L**
