### ISSUE TITLE
Spendings Counter on 

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#5]
### Value Proposition

As a user, I want to access the category pages with more details about my spendings for each category directly from the home page.

### Description

![Bildschirmfoto 2022-11-28 um 15 37 16](https://user-images.githubusercontent.com/115008408/204322752-838c61a3-eed3-46e3-8ebe-77ba9e963af1.png)

### Acceptance Criteria

- [ ] A counter in the category card displays the total amount of spendings for the corresponding category in the current month.

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Display the current month on the category card
- [ ] Create the counter with the total spendings value
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**M**
