### ISSUE TITLE
Spendings Counter on Category Pages

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#6]
### Value Proposition

As a user, I want to see the total amount of spendings for a certain category at a first glance after having accessed the corresponding category page.

### Description

![Bildschirmfoto 2022-11-28 um 17 12 08](https://user-images.githubusercontent.com/115008408/204327509-de36f441-a961-4882-b573-2de1522b4289.png)

### Acceptance Criteria

- [ ] On the category pages, a counter placed in a dedicated card displays the total amount of spendings for the corresponding category in the current month. 

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Create a component with the counter logic
- [ ] Display the counter component in the corresponding category page
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**M**
