### ISSUE TITLE
US2: Add Routes to Navbar Items

### ISSUE THREAD

**Issue by marcos-de-barros-vioque** [marcos-de-barros-vioque/capstone#7]
### Value Proposition

As a user, I want to use the navigation bar to navigate through the different pages of the app.

### Description

![Bildschirmfoto 2022-11-29 um 09 15 11](https://user-images.githubusercontent.com/115008408/204475200-ddf6ffb5-7fd4-43a2-bf2b-a94231b22927.png)

### Acceptance Criteria

 - [ ] Create "Home", "Add spendings", "Tips & Tricks" and "Rewards" pages
 - [ ] The nav items are linked to the corresponding pages
 - [ ] When I am on a certain page, the corresponding nav item should be highlighted
 - [ ] The "Add spendings", "Tips & Tricks" and "Rewards" pages contain "Under construction" messages

### Tasks

- [ ] Pull the remote repository
- [ ] Create a new branch
- [ ] Create routes for "Add spendings", "Tips & Tricks" and "Rewards" pages
- [ ] Add "Under construction" messages to the pages
- [ ] Add, commit and push changes to the remote repository

### Sizing/Complexity

**M**
